loopback: airtap.local
browsers:
  - name: Android
 version: latest
  - name: Android System WebView
 version: 81.0.4044.138
  - name: chrome
 version: latest
  - name: firefox
 version: latest
  - name: safari
 version: latest
  - name: microsoftedge
 version: latest
  - name: iphone
 version: latest
